export const LOAD_STORES = 'LOAD_STORES';

export const LOAD_STORE_TYPES = 'LOAD_STORE_TYPES';

export const LOAD_LOCATIONS = 'LOAD_LOCATIONS';

export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

export const RESET_SEARCH_TERM = 'RESET_SEARCH_TERM';

export const TOGGLE_FILTER_PANEL = 'TOGGLE_FILTER_PANEL';

export const SET_STORE_TYPES = 'SET_STORE_TYPES';

export const TOGGLE_STORE_TYPE = 'TOGGLE_STORE_TYPE';

export const RESET_STORE_TYPES = 'RESET_FILTERS';

export const OPEN_STORE_DETAILS = 'OPEN_STORE_DETAILS';

export const UPDATE_COORDS = "UPDATE_COORDS";

export const TOGGLE_SEARCH_LAYER = 'TOGGLE_SEARCH_LAYER';

export const SET_USER_LOCATION = "SET_USER_LOCATION";

export const SHOW_LOADING = 'SHOW_LOADING';

export const HIDE_LOADING = 'HIDE_LOADING';

export const APPLY_FILTERS = 'APPLY_FILTERS';

export const SET_MAP_INITIAL_COORDS = 'SET_MAP_INITIAL_COORDS';